### PR TITLE
Deathwatch FAQ + Index

### PR DESCRIPTION
**Pull request by Technoblazed**
EDIT: Complete.

### CODE REVIEW

**Comment by derekburgess** [comment]
The suspense! ;P

**Comment by Lake-end** [comment]
> Missing the following units (pending SM update), everything else should be gucci:
> 
> ```
> - captain w/ MCHBR
> - chaplain on bike
> - primaris techmarine
> - heavy intercessors
> - veteran intercessors
> - storm speeder x3
> - land speeder tornadoes
> - land speeder typoons
> - predator destructor
> - predator annihilator
> - gladiator lancer
> - gladiator reaper
> - gladiator valiant
> - hammerfall bunker
> ```

@Technoblazed do you have Paypal or Patreon or something, I could throw few euros/dollars your way so you can buy a beer/coffee on me?

**Comment by Lake-end** [comment]
> The suspense! ;P

@alphalas @DrTobogganMD puh-lease!

**Comment by Technoblazed** [comment]
@derekburgess @Lake-end This is intentionally not being merged as it is still missing a number of SM-library units.

**Pull request merged**
