### PR TITLE
Remove Space Wolves entries duplicated in Space Marines

### PR DESCRIPTION
**Pull request by amis92**
Based on this script: https://gist.github.com/amis92/760757b559e4b070d6c4b037192637cd

@alphalas looks good?

I already added link to SM in Space Wolves, otherwise it wouldn't open correctly in Data Editor.

### CODE REVIEW

**Comment by evertonpendragon** [comment]
Unilits like Intercessors and Infiltrators are not available anymore in SW rosters. How can I add them to my rosters?
Screenshot_20201008-100409

**Comment by alphalas** [comment]
@evertonpendragon Delete your data and stop using prerelease data. This commit is a work in progress and not to be used for list building yet.

**Comment by evertonpendragon** [comment]
Ok @alphalas , I've been using the master files for a while and its the first time it happens, so i thought it was an issue. 
I will use the realesed data instead,
thank you.

**Comment by alphalas** [comment]
We’re working through the new SM indecies and getting the files ready for the codex space marines overhaul which is why files are incomplete now

**Pull request merged**
