### PR TITLE
Fix duplicate Litanies of Hate for DA / Fixed wording of Ability

### PR DESCRIPTION
**Pull request by Toakan**
Fix for /issues/10626

Signed-off-by: Toakan <7566941+Toakan@users.noreply.github.com>

### CODE REVIEW

**Review by Technoblazed — CHANGES_REQUESTED** [review]
This is still technically incorrect, the actual ability name needs to be `Litany of Hate`, not `Litanies of Hate`

**Comment by Toakan** [comment]
Yep, I realised and was already uploading the change :)

**Review by Toakan — COMMENTED** [review]
Done with next push.

**Review by Technoblazed — APPROVED** [review]

**Review by FarseerVeraenthis — APPROVED** [review]
If @Technoblazed is happy then I'm sure it's fine 😸 I noticed this needed doing the other day I've just not gotten around to it :+1: thanks!

**Pull request merged**
