### PR TITLE
T'au Empire 9th edition; QA Hotfixes

### LINKED ISSUE #7399: T'au Empire - 9th edition QA points/PL check for file v60
**File/Catalogue:** T'au Empire v60

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** All errors found during initial QA pass:

- [ ] Dahyak Grekkh is currently 20 points, but should be 40 points
- [ ] The Eight > Commander Brightsword’s MV4 Shield Drones are currently 0 points each, but should be 15 points each
- [ ] MV1 Gun Drones are currently 0 points each, but should be 10 points each on:
1. The Eight > Commander Bravestorm
1. The Eight > Shas’o Sha’vastos
1. The Eight > Shas’o Arra’kon
- [ ] The Eight > Sub-Commander Torchstar’s MV7 Marker Drones are currently 0 points each, but should be 10 points each
- [ ] The Eight > Broadside Shas’vre Ob’loati 9-0’s  MV8 Missile Drones are currently 0 points each, but should be 20 points each
- [ ] The Eight > O’Vesa’s  MV84 Shielded Missile Drones are currently 0 points each, but should be 30 points each
- [ ] Taking 1 or 2 Tactical Drones for a Pathfinder Team should increase its PL by 1
- [ ] Taking either or both of the Support Drones for a Pathfinder Team should increase its PL by 1
- [ ] Taking 1 or 2 Tactical Drones for a Commander in XV81 Crisis Battlesuit should increase its PL by 1
- [ ] Taking 1 or 2 Tactical Drones for a Commander in XV84 Crisis Battlesuit should increase its PL by 1
- [ ] Taking any Tactical Drones for a XV9 Hazard Support Team should increase its PL by 1 per drone
- [ ] Tiger Shark’s swiftstrike railgun is currently 101 points each, but should be 5 points each

### PR DESCRIPTION
**Pull request by Technoblazed**
This should resolve all the issues pointed out by Dunamis in https://github.com/BSData/wh40k/issues/7399.

Closes #7399 in the process.

### CODE REVIEW

**Comment by amis92** [comment]
I'm pretty sure The Eight's cost includes drones. So I'd like you to revert that part. 😊

**Review by amis92 — CHANGES_REQUESTED** [review]
The Eight's drones should still be free, IMO.

**Comment by Technoblazed** [comment]
Per the manual, it's specifically under the section that says "excludes drones". What's weird is that the point the icon that specifies that the units in that section include drone costs, aren't used at all in the document. Whether or not this is a mistake or not, RAW they don't include drone costs.

**Comment by amis92** [comment]
RAW The Eight is listed as:
> 8 models, 14 drones

It has a cost of 1250 **POINTS/MODEL**, and that section is also marked as _includes wargear but not drones_.

As such it's 8 models x 1250pts/model = 10000 pts, not counting 14 drones.

😊 I think we can agree it's makes no sense. As such, I'm taking on an **Assumed Amendment** for this listing to _make_ sense: 1250pts is the total cost of the unit including drones.

**Review by amis92 — APPROVED** [review]

**Comment by amis92** [comment]
Thanks a lot!

**Pull request merged**
