### PR TITLE
Finished adding all FW astartes characters

### PR DESCRIPTION
**Pull request by ddarz**
All the astartes characters have been added. The two inquisitor characters have been left out as they are to be added into the inquisition cat.

### CODE REVIEW

**Comment by ddarz** [comment]
Name change done :)

**Comment by frohawk8337** [comment]
FW characters look good.  Will this be integrated Into space marines cat? Or referenced as with the current set up you cannot create a list using any FW characters as hqs.

**Comment by amis92** [comment]
@frohawk8337 see #77

**Comment by frohawk8337** [comment]
Got it thanks!

**Pull request merged**
