### PR TITLE
Leagues of Votann

### PR DESCRIPTION
**Pull request by raddue**
Pushin' to master.  Mastering that pushing.

### CODE REVIEW

**Comment by AbonShell** [comment]
Already being worked on by a data developer, as well as we can't release it before the book comes out.

**Comment by alphalas** [comment]
Also, as a rule, we do not accept unsolicited changes unless they’re very minor bug fixes and the author talks to the Data Authors first.

**Comment by raddue** [comment]
Understandable on both counts.

The data developer might be able to use this file, then.  It should be everything barring some minor typos that might still exist.

**Comment by Mad-Spy** [comment]
Hi, I'm the one who has done the implementation for the Votann Codex.

This is a really good start, but it is missing a bunch of stuff, mostly around validation (although there are also a few point/PL values missing).

If you're on the Discord, come say hi and I can let you have my version so you can compare.

**Comment by raddue** [comment]
@Mad-Spy -- I'm over there under the monkier "Raddue". Thank you for the generous offer!

**Pull request closed without merging**
