### PR TITLE
Fix: Typos - Inquisition

### PR DESCRIPTION
**Pull request by dixhuit**
Fixed some typos & punctuation in Inquisition Shared Profiles.

### CODE REVIEW

**Comment by dixhuit** [comment]
Am learning the ropes here in terms of BSData's process, please let me know if I've done anything wrong and I'll try to fix it. Just noticed that I haven't included an incremented revision number, is that something you expect as part of the PR?

**Comment by Mad-Spy** [comment]
Yes, please do increment the file revision. You also seem to have unnecessarily changed the gameSystemRevision.

**Comment by dixhuit** [comment]
@Mad-Spy OK, thanks for the info. I didn't knowingly change `gameSystemRevision`, this must have been the Data Editor. How can I avoid this? I am using an older version of Battlescribe, is that the issue?

**Comment by Mad-Spy** [comment]
Yes. Please update to the latest version of Battlescribe.

**Comment by dixhuit** [comment]
Gaagh, had a feeling you'd say that, the new version seems to have a bad memory leak on my system. Righto, will do. I'll update the PR later.

**Comment by Mad-Spy** [comment]
There's also functionality in the newer versions which will not work with the old one, so you'll have testing issues if you plan to do more data work.

**Comment by dixhuit** [comment]
Sorry, got busy and you beat me to it. I now know more for next time though so thanks!

**Pull request merged**
