### PR TITLE
Added KX139 Supremacy armor unit stats in

### PR DESCRIPTION
**Pull request by DarienFord**
They were not linked to the profile correctly.

### CODE REVIEW

**Comment by acebaur** [comment]
Unfortunately we are not open source. We use github for convenience but Battlescribe does bad things when multiple people work on the same cat

**Comment by DarienFord** [comment]
Ahh ok; so should I just open an issue?

**Comment by Technoblazed** [comment]
@DarienFord what exactly was changed here? The stats are showing up fine on the profile on the latest master data.

**Comment by DarienFord** [comment]
I just realized the data I pull down in Battlescribe is not from master but github releases.
I also just spent a bunch of time trying to get the master version to load in Battlescribe but there seems to be challenges with using it directly from source in windows.

I'll wait until there is a new release before filing any issue.

**Pull request closed without merging**
