### PR TITLE
fix: Discord Invite Link

### PR DESCRIPTION
**Pull request by amis92**
The currently used one was lost to the Warp.

### CODE REVIEW

**Review by Technoblazed — APPROVED** [review]
Needs more ducks, but LGTM

**Review by Thairne — APPROVED** [review]
The Toasters also would like to express their approval.

**Review by alphalas — APPROVED** [review]
I mean if it needs done it needs done.

**Review by DrTobogganMD — APPROVED** [review]

**Comment by amis92** [comment]
After discussing on the mod level, we agreed on acquiring our own domain, so we'll update the links after we do that.

**Pull request closed without merging**
