### PR TITLE
Ork changes to 9th

### PR DESCRIPTION
**Pull request by CaptainGelb**
**The FAQ Changes** from Indomitus Version 1.0 from the 13/07/2020 Update

**Point Changes from the Leaks**
Big Mek in Mega Armor	77 85
Grot oiler	4 5
Big Mek in Shokk attack gun 55 95
Big Mek with Kustom Force Field 55 60
Deffkilla Wartrike 120 125
Warboss 65 70
Weirdboy 62 75

Boyz	7	8
Gretchin	3	5

Boomdakka Snazzwagon	75	85
Deffkoptas	20	25
Kustom Boosta-blasta	80	90
Megatrakk Scrapjets	80	90
Rukkatrukk Squigbuggies	100	110
Shokkjump Dragsta	90	100
Stormboyz	9	12
Warbikers	23	27

Burna boyz	10	11
Kommandos	8	9
Meganobz	20	25
Mek	22	25
grot oiler	4	5
Nob with WAAAGH! Banner	75	85
Nobz	14	17
Ammo runt	4	5
Nobz on warbikes	33	35
Painboy	52	55
Runtherd	35	40
Tankbustas	5	7
Bomb squigs	10	10

Battlewagon	120	135
Bonebreaka	140	160
Deff Dreads	45	55
Flash Gitz	24	32
Ammo runts	4	5
Gorkanaut	250	285
Gunwagon	140	160
Killa Kans	30	45
Lootas	17	20
Mek Gunz (inc crew)	15	20
Morkanaut	220	270

Trukk	59	60

Blitza-bommer	108	130
Burna-bommer	102	125
Dakkajet	88	110
Wazbom Blastajet	99	140

Stompa	800	850

Mekboy Workshop	80	85

Boss Snikrot	70	75
Boss Zagstruk	88	95
Ghazghkull thraka	285	300
Kaptain Badrukk	84	90
ammo runt	4	5
Mad Dok Grotsnik	86	90
makari	65	65

Big shoota	5	5
Bubblechukka	30	30
Burna	0	0
Burna bottles	0	0
Burna exhaust	0	0
Dakkagun	0	0
Deffgun	0	0
Deffkannon	0	0
Deffstorm mega-shoota	0	0
Grot blasta	0	0
Grotzooka	10	10
Heavy Squig launcha	0	0
Kannon	15	15
Killa jet	0	0
Killakannon	15	15
Kombi-weapon with rokkit launcha	12	10
Kombi-weapon with skorcha	17	15
Kopta rokkits	24	25
Kustom mega-blasta	9	10
Kustom mega-kannon	45	45
Kustom mega-slugga	7	5
Kustom mega-zappa	17	0
Kustom shokk rifle	0	0
Kustom shoota	2	3
Lobba	18	20
Mek speshul	0	0
Rivet Kannon	0	0
Rokkit kannon	0	0
Rokkit launcha	12	10
Pair of rokkit pistols	12	10
Shokk attack gun	25	25
Shoota	0	0
Shotgun	0	0
Skorcha	17	15
Skorcha missiles	5	10
Slugga	0	0
Smasha gun	18	20
Snagga klaw	0	0
Snazzgun	0	0
Squig bomb	0	0
Squig launcha	0	0
Stikkbomb chukka	5	5
Stikkbomb flinga	4	5
Stikkbombs	0	0
Stikksquig	0	0
Supa-shoota	10	10
Supa-gatler	28	0
Supa-rokkit	0	5
Tankbusta bombs	0	0
Tellyport blasta	11	10
Tellyport mega-blasta	18	10
Traktor kannon	30	30
Twin big shoota	10	10
Twin boomstikk	0	0
Wazbom mega-kannon	12	0
Wing missiles	0	0
Zzap gun	18	15

Attack squig	0	0
Big choppa	5	5
Buzz saw	0	0
Choppa	0	0
Deff rolla	19	20
Dread klaw	15	15
Dread saw	10	10
Drilla	0	0
Grabba stikk	0	0
Grabbin' klaw	5	5
Grot-prod	0	0
Kan klaw	0	0
Killsaw	15	10
2 Killsaws	23	15
Klaw of Gork	0	0
Mega-choppa	0	0
Nose drill	0	0
Power klaw	13	10
Power stabba	3	5
Saw blades	0	0
Spinnin' blades	0	0
Tankhammer	10	10
Urty syringe	0	0
WAAAGH! banner	0	0
Weirdboy staff	0	0
Wreckin' ball	3	5

Ard case	0	0
Cybork body	5	5
Gitfinda squig	0	0
Grot lash	0	0
Grot rigger	5	5
Kustom force field	20	20
Squig hound	0	0

### CODE REVIEW

**Comment by alphalas** [comment]
@CaptainGelb PLEASE talk to us on the discord before making unsolicited pull reqs.

**Comment by tag8833** [comment]
It looks like @CaptainGelb did a good job here.  

The only error I've found so far is the Burna Bommer.  (New points is 125).   

@CaptainGelb I appreciate the help, and I'm am going to commit your updated file with only that one change.

**Comment by CaptainGelb** [comment]
Won't happen again. I am new to git and the BSData Community.

**Comment by amis92** [comment]
@CaptainGelb not sure we're in understanding. Ork maintainer said he'll use your work. He just found a single error he's going to fix. All is well. Nothing to be sorry about. 😊

**Comment by tag8833** [comment]
Yeah, I appreciate the help.  My work has been chaotic because of Covid-19, and so I hadn't gotten around to it as soon as I had hoped.   Just drop me a private message on discord if you want to help on it next time.

**Pull request closed without merging**
