### PR TITLE
necrons typo fixes

### PR DESCRIPTION
**Pull request by barneschism**
various typo fixes for necrons

### CODE REVIEW

**Comment by DrTobogganMD** [comment]
Always make sure to bump the revision number when making changes. Otherwise BS won't update the file.  Bump that, and recommit - otherwise looks good.

**Review by DrTobogganMD — CHANGES_REQUESTED** [review]
Always make sure to bump the revision number when making changes. Otherwise BS won't update the file. Bump that, and recommit - otherwise looks good.

**Comment by barneschism** [comment]
Cool deal, hope i updated the correct revision number

**Review by DrTobogganMD — APPROVED** [review]
Yep, good job.

**Pull request merged**
