### PR TITLE
New primaries

### PR DESCRIPTION
**Pull request by Mad-Spy**
- Added new categories for "Configuration" and "Stratagems" to all Force Entries
- Recategorised relevant GST SSEs

- Updated all Chaos catalogues to new format as an example.

### CODE REVIEW

**Comment by GenWilhelm** [comment]
There are many duplicate IDs on the category links in the GST. Is the data editor okay with this?

**Comment by Mad-Spy** [comment]
@GenWilhelm, it doesn't complain, but I've regenerated them to make sure.

**Comment by amis92** [comment]
If it doesn't break rosters, well, LGTM.

Also, linking #6733

Do you plan to update all the other catalogues as part of this PR, or do you leave it to every cat owner?

**Review by amis92 — APPROVED** [review]

**Comment by DrTobogganMD** [comment]
> If it doesn't break rosters, well, LGTM.

I'm thinking it might, but that's not avoidable I think? We're changing root categories of items people may have in their roster, which shouldn't break, but if we split them out into brand new categories as planned, that would break lists.

**Review by DrTobogganMD — APPROVED** [review]

**Comment by amis92** [comment]
I mean I think Mad-Spy already confirmed it doesn't so it was more a rhetorical condition. :)

**Comment by Mad-Spy** [comment]
I think I got all of the obvious ones. I'm going to merge, but please check your catalogues.

**Pull request merged**
